/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youle_cosmetology_jni_CureJniFaceRecognition */

#ifndef _Included_com_youle_cosmetology_jni_CureJniFaceRecognition
#define _Included_com_youle_cosmetology_jni_CureJniFaceRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youle_cosmetology_jni_CureJniFaceRecognition
 * Method:    recogni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 * !!!!!!!!!!!!!!!!!!!!!!!!Format: Java_ClassName_MethodName
 */
JNIEXPORT jstring JNICALL Java_com_youle_cosmetology_jni_CureJniFaceRecognition_recogni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
