/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_utils_des_DesTools */

#ifndef _Included_com_jni_utils_des_DesTools
#define _Included_com_jni_utils_des_DesTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_utils_des_DesTools
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_utils_des_DesTools_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_utils_des_DesTools
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_utils_des_DesTools_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
