/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CureFaceParser */

#ifndef _Included_CureFaceParser
#define _Included_CureFaceParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CureFaceParser
 * Method:    getFaceParseResult
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CureFaceParser_getFaceParseResult
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
