/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youle_jni_FaceRecognition */

#ifndef _Included_com_youle_jni_FaceRecognition
#define _Included_com_youle_jni_FaceRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youle_jni_FaceRecognition
 * Method:    recogni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FaceRecognition_recogni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
